#include "native_hooks.h"


#include "ParagonMoney.h"
#include "game/backend/NativeHooks.hpp"
#include "game/gta/Natives.hpp"
#include "types/game_files/CNetworkShoppingMgr.h"

namespace YimMenu
{
	void ParagonNativeHooks::Init()
	{
		// TODO: Fix server stat DB so we don't need this: only affects Enhanced
		NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::STAT_GET_LOAD_SAFE_TO_PROGRESS_TO_MP_FROM_SP, ProgressMpSp);
		NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NET_GAMESERVER_USE_SERVER_TRANSACTIONS, UseTransactions);
		NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::STAT_GET_INT, StatGetInt);
		// LOG(INFO) << (*Pointers.TransactionMgr)->ShouldDoNullTransaction() << " << Null Transaction";
		// LOG(INFO) << NETSHOPPING::NET_GAMESERVER_USE_SERVER_TRANSACTIONS() << " Server Transactions";
		// LOG(INFO) << NETSHOPPING::
		// AUTOGENERATED
		// NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_PICKUP, ParagonMoney::NETWORK_EARN_FROM_PICKUP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_CASHING_OUT, ParagonMoney::NETWORK_EARN_FROM_CASHING_OUT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_GANGATTACK_PICKUP, ParagonMoney::NETWORK_EARN_FROM_GANGATTACK_PICKUP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ASSASSINATE_TARGET_KILLED, ParagonMoney::NETWORK_EARN_ASSASSINATE_TARGET_KILLED);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_ROB_ARMORED_CARS, ParagonMoney::NETWORK_EARN_FROM_ROB_ARMORED_CARS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_CRATE_DROP, ParagonMoney::NETWORK_EARN_FROM_CRATE_DROP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_BETTING, ParagonMoney::NETWORK_EARN_FROM_BETTING);
	 // NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_JOB, ParagonMoney::NETWORK_EARN_FROM_JOB);
	 // NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_JOBX2, ParagonMoney::NETWORK_EARN_FROM_JOBX2);
	 // NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_PREMIUM_JOB, ParagonMoney::NETWORK_EARN_FROM_PREMIUM_JOB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_BEND_JOB, ParagonMoney::NETWORK_EARN_FROM_BEND_JOB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_CHALLENGE_WIN, ParagonMoney::NETWORK_EARN_FROM_CHALLENGE_WIN);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_BOUNTY, ParagonMoney::NETWORK_EARN_FROM_BOUNTY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_IMPORT_EXPORT, ParagonMoney::NETWORK_EARN_FROM_IMPORT_EXPORT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_HOLDUPS, ParagonMoney::NETWORK_EARN_FROM_HOLDUPS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_PROPERTY, ParagonMoney::NETWORK_EARN_FROM_PROPERTY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_AI_TARGET_KILL, ParagonMoney::NETWORK_EARN_FROM_AI_TARGET_KILL);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_NOT_BADSPORT, ParagonMoney::NETWORK_EARN_FROM_NOT_BADSPORT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_VEHICLE, ParagonMoney::NETWORK_EARN_FROM_VEHICLE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_PERSONAL_VEHICLE, ParagonMoney::NETWORK_EARN_FROM_PERSONAL_VEHICLE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_DAILY_OBJECTIVES, ParagonMoney::NETWORK_EARN_FROM_DAILY_OBJECTIVES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_AMBIENT_JOB, ParagonMoney::NETWORK_EARN_FROM_AMBIENT_JOB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_JOB_BONUS, ParagonMoney::NETWORK_EARN_FROM_JOB_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_CRIMINAL_MASTERMIND, ParagonMoney::NETWORK_EARN_FROM_CRIMINAL_MASTERMIND);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_HEIST_AWARD, ParagonMoney::NETWORK_EARN_HEIST_AWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FIRST_TIME_BONUS, ParagonMoney::NETWORK_EARN_FIRST_TIME_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GOON, ParagonMoney::NETWORK_EARN_GOON);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_BOSS, ParagonMoney::NETWORK_EARN_BOSS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AGENCY, ParagonMoney::NETWORK_EARN_AGENCY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_WAREHOUSE, ParagonMoney::NETWORK_EARN_FROM_WAREHOUSE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_CONTRABAND, ParagonMoney::NETWORK_EARN_FROM_CONTRABAND);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_DESTROYING_CONTRABAND, ParagonMoney::NETWORK_EARN_FROM_DESTROYING_CONTRABAND);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_SMUGGLER_WORK, ParagonMoney::NETWORK_EARN_FROM_SMUGGLER_WORK);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_HANGAR_TRADE, ParagonMoney::NETWORK_EARN_FROM_HANGAR_TRADE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_PURCHASE_CLUB_HOUSE, ParagonMoney::NETWORK_EARN_PURCHASE_CLUB_HOUSE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_BUSINESS_PRODUCT, ParagonMoney::NETWORK_EARN_FROM_BUSINESS_PRODUCT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_VEHICLE_EXPORT, ParagonMoney::NETWORK_EARN_FROM_VEHICLE_EXPORT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_SMUGGLER_AGENCY, ParagonMoney::NETWORK_EARN_SMUGGLER_AGENCY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_BOUNTY_HUNTER_REWARD, ParagonMoney::NETWORK_EARN_BOUNTY_HUNTER_REWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_BUSINESS_BATTLE, ParagonMoney::NETWORK_EARN_FROM_BUSINESS_BATTLE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_CLUB_MANAGEMENT_PARTICIPATION, ParagonMoney::NETWORK_EARN_FROM_CLUB_MANAGEMENT_PARTICIPATION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_FMBB_PHONECALL_MISSION, ParagonMoney::NETWORK_EARN_FROM_FMBB_PHONECALL_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_BUSINESS_HUB_SELL, ParagonMoney::NETWORK_EARN_FROM_BUSINESS_HUB_SELL);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_FMBB_BOSS_WORK, ParagonMoney::NETWORK_EARN_FROM_FMBB_BOSS_WORK);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FMBB_WAGE_BONUS, ParagonMoney::NETWORK_EARN_FMBB_WAGE_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_GOON, ParagonMoney::NETWORK_SPEND_GOON);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BOSS, ParagonMoney::NETWORK_SPEND_BOSS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_SELL_BUNKER, ParagonMoney::NETWORK_EARN_FROM_SELL_BUNKER);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_RDR_BONUS, ParagonMoney::NETWORK_EARN_RDR_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_WAGE_PAYMENT, ParagonMoney::NETWORK_EARN_WAGE_PAYMENT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_WAGE_PAYMENT_BONUS, ParagonMoney::NETWORK_EARN_WAGE_PAYMENT_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_GANGOPS_CANNON, ParagonMoney::NETWORK_SPEND_GANGOPS_CANNON);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_GANGOPS_SKIP_MISSION, ParagonMoney::NETWORK_SPEND_GANGOPS_SKIP_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CASINO_HEIST_SKIP_MISSION, ParagonMoney::NETWORK_SPEND_CASINO_HEIST_SKIP_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_SELL_BASE, ParagonMoney::NETWORK_EARN_SELL_BASE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_TARGET_REFUND, ParagonMoney::NETWORK_EARN_TARGET_REFUND);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GANGOPS_WAGES, ParagonMoney::NETWORK_EARN_GANGOPS_WAGES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GANGOPS_WAGES_BONUS, ParagonMoney::NETWORK_EARN_GANGOPS_WAGES_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_DAR_CHALLENGE, ParagonMoney::NETWORK_EARN_DAR_CHALLENGE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_DOOMSDAY_FINALE_BONUS, ParagonMoney::NETWORK_EARN_DOOMSDAY_FINALE_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GANGOPS_AWARD, ParagonMoney::NETWORK_EARN_GANGOPS_AWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GANGOPS_ELITE, ParagonMoney::NETWORK_EARN_GANGOPS_ELITE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SERVICE_EARN_GANGOPS_RIVAL_DELIVERY, ParagonMoney::NETWORK_SERVICE_EARN_GANGOPS_RIVAL_DELIVERY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_GANGOPS_START_STRAND, ParagonMoney::NETWORK_SPEND_GANGOPS_START_STRAND);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_GANGOPS_TRIP_SKIP, ParagonMoney::NETWORK_SPEND_GANGOPS_TRIP_SKIP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GANGOPS_PREP_PARTICIPATION, ParagonMoney::NETWORK_EARN_GANGOPS_PREP_PARTICIPATION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GANGOPS_SETUP, ParagonMoney::NETWORK_EARN_GANGOPS_SETUP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_GANGOPS_FINALE, ParagonMoney::NETWORK_EARN_GANGOPS_FINALE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_GANGOPS_REPAIR_COST, ParagonMoney::NETWORK_SPEND_GANGOPS_REPAIR_COST);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_NIGHTCLUB, ParagonMoney::NETWORK_EARN_NIGHTCLUB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_NIGHTCLUB_DANCING, ParagonMoney::NETWORK_EARN_NIGHTCLUB_DANCING);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_BB_EVENT_BONUS, ParagonMoney::NETWORK_EARN_BB_EVENT_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_HACKER_TRUCK, ParagonMoney::NETWORK_EARN_HACKER_TRUCK);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_NIGHTCLUB_AND_WAREHOUSE, ParagonMoney::NETWORK_EARN_NIGHTCLUB_AND_WAREHOUSE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_NIGHTCLUB_AND_WAREHOUSE, ParagonMoney::NETWORK_SPEND_NIGHTCLUB_AND_WAREHOUSE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_NIGHTCLUB_BAR_DRINK, ParagonMoney::NETWORK_SPEND_NIGHTCLUB_BAR_DRINK);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BOUNTY_HUNTER_MISSION, ParagonMoney::NETWORK_SPEND_BOUNTY_HUNTER_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ARENA_SKILL_LEVEL_PROGRESSION, ParagonMoney::NETWORK_EARN_ARENA_SKILL_LEVEL_PROGRESSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ARENA_CAREER_PROGRESSION, ParagonMoney::NETWORK_EARN_ARENA_CAREER_PROGRESSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_MAKE_IT_RAIN, ParagonMoney::NETWORK_SPEND_MAKE_IT_RAIN);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BUY_ARENA, ParagonMoney::NETWORK_SPEND_BUY_ARENA);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_UPGRADE_ARENA, ParagonMoney::NETWORK_SPEND_UPGRADE_ARENA);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_ARENA_SPECTATOR_BOX, ParagonMoney::NETWORK_SPEND_ARENA_SPECTATOR_BOX);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_SPIN_THE_WHEEL_PAYMENT, ParagonMoney::NETWORK_SPEND_SPIN_THE_WHEEL_PAYMENT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_SPIN_THE_WHEEL_CASH, ParagonMoney::NETWORK_EARN_SPIN_THE_WHEEL_CASH);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_ARENA_PREMIUM, ParagonMoney::NETWORK_SPEND_ARENA_PREMIUM);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ARENA_WAR, ParagonMoney::NETWORK_EARN_ARENA_WAR);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ARENA_WAR_ASSASSINATE_TARGET, ParagonMoney::NETWORK_EARN_ARENA_WAR_ASSASSINATE_TARGET);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ARENA_WAR_EVENT_CARGO, ParagonMoney::NETWORK_EARN_ARENA_WAR_EVENT_CARGO);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_RC_TIME_TRIAL, ParagonMoney::NETWORK_EARN_RC_TIME_TRIAL);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_DAILY_OBJECTIVE_EVENT, ParagonMoney::NETWORK_EARN_DAILY_OBJECTIVE_EVENT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CASINO_MEMBERSHIP, ParagonMoney::NETWORK_SPEND_CASINO_MEMBERSHIP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BUY_CASINO, ParagonMoney::NETWORK_SPEND_BUY_CASINO);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_UPGRADE_CASINO, ParagonMoney::NETWORK_SPEND_UPGRADE_CASINO);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CASINO_GENERIC, ParagonMoney::NETWORK_SPEND_CASINO_GENERIC);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_TIME_TRIAL_WIN, ParagonMoney::NETWORK_EARN_CASINO_TIME_TRIAL_WIN);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_COLLECTABLES_ACTION_FIGURES, ParagonMoney::NETWORK_EARN_COLLECTABLES_ACTION_FIGURES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_COLLECTABLE_COMPLETED_COLLECTION, ParagonMoney::NETWORK_EARN_CASINO_COLLECTABLE_COMPLETED_COLLECTION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_SELL_PRIZE_VEHICLE, ParagonMoney::NETWORK_EARN_SELL_PRIZE_VEHICLE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_MISSION_REWARD, ParagonMoney::NETWORK_EARN_CASINO_MISSION_REWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_STORY_MISSION_REWARD, ParagonMoney::NETWORK_EARN_CASINO_STORY_MISSION_REWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_MISSION_PARTICIPATION, ParagonMoney::NETWORK_EARN_CASINO_MISSION_PARTICIPATION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_AWARD, ParagonMoney::NETWORK_EARN_CASINO_AWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BUY_ARCADE, ParagonMoney::NETWORK_SPEND_BUY_ARCADE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_UPGRADE_ARCADE, ParagonMoney::NETWORK_SPEND_UPGRADE_ARCADE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CASINO_HEIST, ParagonMoney::NETWORK_SPEND_CASINO_HEIST);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_ARCADE_MGMT, ParagonMoney::NETWORK_SPEND_ARCADE_MGMT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_PLAY_ARCADE, ParagonMoney::NETWORK_SPEND_PLAY_ARCADE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_ARCADE, ParagonMoney::NETWORK_SPEND_ARCADE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_HEIST, ParagonMoney::NETWORK_EARN_CASINO_HEIST);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_UPGRADE_ARCADE, ParagonMoney::NETWORK_EARN_UPGRADE_ARCADE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ARCADE, ParagonMoney::NETWORK_EARN_ARCADE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_COLLECTABLES, ParagonMoney::NETWORK_EARN_COLLECTABLES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CHALLENGE, ParagonMoney::NETWORK_EARN_CHALLENGE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CASINO_HEIST_AWARDS, ParagonMoney::NETWORK_EARN_CASINO_HEIST_AWARDS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_COLLECTABLE_ITEM, ParagonMoney::NETWORK_EARN_COLLECTABLE_ITEM);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_COLLECTABLE_COMPLETED_COLLECTION, ParagonMoney::NETWORK_EARN_COLLECTABLE_COMPLETED_COLLECTION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_YATCH_MISSION, ParagonMoney::NETWORK_EARN_YATCH_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_DISPATCH_CALL, ParagonMoney::NETWORK_EARN_DISPATCH_CALL);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BEACH_PARTY, ParagonMoney::NETWORK_SPEND_BEACH_PARTY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_SUBMARINE, ParagonMoney::NETWORK_SPEND_SUBMARINE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CASINO_CLUB, ParagonMoney::NETWORK_SPEND_CASINO_CLUB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BUY_SUB, ParagonMoney::NETWORK_SPEND_BUY_SUB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_UPGRADE_SUB, ParagonMoney::NETWORK_SPEND_UPGRADE_SUB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_ISLAND_HEIST, ParagonMoney::NETWORK_SPEND_ISLAND_HEIST);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_ISLAND_HEIST, ParagonMoney::NETWORK_EARN_ISLAND_HEIST);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_BEACH_PARTY_LOST_FOUND, ParagonMoney::NETWORK_EARN_BEACH_PARTY_LOST_FOUND);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FROM_ISLAND_HEIST_DJ_MISSION, ParagonMoney::NETWORK_EARN_FROM_ISLAND_HEIST_DJ_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CAR_CLUB_MEMBERSHIP, ParagonMoney::NETWORK_SPEND_CAR_CLUB_MEMBERSHIP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CAR_CLUB_BAR, ParagonMoney::NETWORK_SPEND_CAR_CLUB_BAR);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_AUTOSHOP_MODIFY, ParagonMoney::NETWORK_SPEND_AUTOSHOP_MODIFY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_CAR_CLUB_TAKEOVER, ParagonMoney::NETWORK_SPEND_CAR_CLUB_TAKEOVER);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BUY_AUTOSHOP, ParagonMoney::NETWORK_SPEND_BUY_AUTOSHOP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_UPGRADE_AUTOSHOP, ParagonMoney::NETWORK_SPEND_UPGRADE_AUTOSHOP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AUTOSHOP_BUSINESS, ParagonMoney::NETWORK_EARN_AUTOSHOP_BUSINESS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AUTOSHOP_INCOME, ParagonMoney::NETWORK_EARN_AUTOSHOP_INCOME);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_CARCLUB_MEMBERSHIP, ParagonMoney::NETWORK_EARN_CARCLUB_MEMBERSHIP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_DAILY_VEHICLE, ParagonMoney::NETWORK_EARN_DAILY_VEHICLE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_DAILY_VEHICLE_BONUS, ParagonMoney::NETWORK_EARN_DAILY_VEHICLE_BONUS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_TUNER_AWARD, ParagonMoney::NETWORK_EARN_TUNER_AWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_TUNER_ROBBERY, ParagonMoney::NETWORK_EARN_TUNER_ROBBERY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_UPGRADE_AUTOSHOP, ParagonMoney::NETWORK_EARN_UPGRADE_AUTOSHOP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_INTERACTION_MENU_ABILITY, ParagonMoney::NETWORK_SPEND_INTERACTION_MENU_ABILITY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BUY_AGENCY, ParagonMoney::NETWORK_SPEND_BUY_AGENCY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_UPGRADE_AGENCY, ParagonMoney::NETWORK_SPEND_UPGRADE_AGENCY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_AGENCY, ParagonMoney::NETWORK_SPEND_AGENCY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_HIDDEN, ParagonMoney::NETWORK_SPEND_HIDDEN);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_SOURCE_BIKE, ParagonMoney::NETWORK_SPEND_SOURCE_BIKE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_COMP_SUV, ParagonMoney::NETWORK_SPEND_COMP_SUV);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_SUV_FST_TRVL, ParagonMoney::NETWORK_SPEND_SUV_FST_TRVL);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_SUPPLY, ParagonMoney::NETWORK_SPEND_SUPPLY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BIKE_SHOP, ParagonMoney::NETWORK_SPEND_BIKE_SHOP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_VEHICLE_REQUESTED, ParagonMoney::NETWORK_SPEND_VEHICLE_REQUESTED);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_GUNRUNNING, ParagonMoney::NETWORK_SPEND_GUNRUNNING);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AGENCY_SAFE, ParagonMoney::NETWORK_EARN_AGENCY_SAFE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AWARD_CONTRACT, ParagonMoney::NETWORK_EARN_AWARD_CONTRACT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AGENCY_CONTRACT, ParagonMoney::NETWORK_EARN_AGENCY_CONTRACT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AWARD_PHONE, ParagonMoney::NETWORK_EARN_AWARD_PHONE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AGENCY_PHONE, ParagonMoney::NETWORK_EARN_AGENCY_PHONE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AWARD_FIXER_MISSION, ParagonMoney::NETWORK_EARN_AWARD_FIXER_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FIXER_PREP, ParagonMoney::NETWORK_EARN_FIXER_PREP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FIXER_FINALE, ParagonMoney::NETWORK_EARN_FIXER_FINALE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FIXER_AGENCY_SHORT_TRIP, ParagonMoney::NETWORK_EARN_FIXER_AGENCY_SHORT_TRIP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_AWARD_SHORT_TRIP, ParagonMoney::NETWORK_EARN_AWARD_SHORT_TRIP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_FIXER_RIVAL_DELIVERY, ParagonMoney::NETWORK_EARN_FIXER_RIVAL_DELIVERY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_UPGRADE_AGENCY, ParagonMoney::NETWORK_EARN_UPGRADE_AGENCY);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_APARTMENT_UTILITIES, ParagonMoney::NETWORK_SPEND_APARTMENT_UTILITIES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_SPEND_BUSINESS_PROPERTY_FEES, ParagonMoney::NETWORK_SPEND_BUSINESS_PROPERTY_FEES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_SIGHTSEEING_REWARD, ParagonMoney::NETWORK_EARN_SIGHTSEEING_REWARD);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_BIKER_SHOP, ParagonMoney::NETWORK_EARN_BIKER_SHOP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::NETWORK_EARN_BIKER, ParagonMoney::NETWORK_EARN_BIKER);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_BUY_MFGARAGE, ParagonMoney::_NETWORK_SPEND_BUY_MFGARAGE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_UPGRADE_MFGARAGE, ParagonMoney::_NETWORK_SPEND_UPGRADE_MFGARAGE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_BUY_SUPPLIES, ParagonMoney::_NETWORK_SPEND_BUY_SUPPLIES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_BUY_ACID_LAB, ParagonMoney::_NETWORK_SPEND_BUY_ACID_LAB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_UPGRADE_ACID_LAB_EQUIPMENT, ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_EQUIPMENT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_UPGRADE_ACID_LAB_ARMOR, ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_ARMOR);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_UPGRADE_ACID_LAB_SCOOP, ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_SCOOP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_UPGRADE_ACID_LAB_MINES, ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_MINES);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_RENAME_ACID_LAB, ParagonMoney::_NETWORK_SPEND_RENAME_ACID_LAB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_SPEND_RENAME_ACID_PRODUCT, ParagonMoney::_NETWORK_SPEND_RENAME_ACID_PRODUCT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_AWARD_JUGGALO_MISSION, ParagonMoney::_NETWORK_EARN_AWARD_JUGGALO_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_AWARD_ACID_LAB, ParagonMoney::_NETWORK_EARN_AWARD_ACID_LAB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_AWARD_DAILY_STASH, ParagonMoney::_NETWORK_EARN_AWARD_DAILY_STASH);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_AWARD_DEAD_DROP, ParagonMoney::_NETWORK_EARN_AWARD_DEAD_DROP);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_AWARD_RANDOM_EVENT, ParagonMoney::_NETWORK_EARN_AWARD_RANDOM_EVENT);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_AWARD_TAXI, ParagonMoney::_NETWORK_EARN_AWARD_TAXI);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_STREET_DEALER, ParagonMoney::_NETWORK_EARN_STREET_DEALER);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_SELL_ACID, ParagonMoney::_NETWORK_EARN_SELL_ACID);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_SETUP_PARTICIPATION_ACID_LAB, ParagonMoney::_NETWORK_EARN_SETUP_PARTICIPATION_ACID_LAB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_SOURCE_PARTICIPATION_ACID_LAB, ParagonMoney::_NETWORK_EARN_SOURCE_PARTICIPATION_ACID_LAB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_SELL_PARTICIPATION_ACID_LAB, ParagonMoney::_NETWORK_EARN_SELL_PARTICIPATION_ACID_LAB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_JUGGALO_STORY_MISSION, ParagonMoney::_NETWORK_EARN_JUGGALO_STORY_MISSION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_JUGGALO_STORY_MISSION_PARTICIPATION, ParagonMoney::_NETWORK_EARN_JUGGALO_STORY_MISSION_PARTICIPATION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_FOOLIGAN_JOB, ParagonMoney::_NETWORK_EARN_FOOLIGAN_JOB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_FOOLIGAN_JOB_PARTICIPATION, ParagonMoney::_NETWORK_EARN_FOOLIGAN_JOB_PARTICIPATION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_TAXI_JOB, ParagonMoney::_NETWORK_EARN_TAXI_JOB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_DAILY_STASH_HOUSE_COMPLETED, ParagonMoney::_NETWORK_EARN_DAILY_STASH_HOUSE_COMPLETED);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_DAILY_STASH_HOUSE_PARTICIPATION, ParagonMoney::_NETWORK_EARN_DAILY_STASH_HOUSE_PARTICIPATION);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_AVENGER, ParagonMoney::_NETWORK_EARN_AVENGER);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_SMUGGLER_OPS, ParagonMoney::_NETWORK_EARN_SMUGGLER_OPS);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_BONUS_OBJECTIVE, ParagonMoney::_NETWORK_EARN_BONUS_OBJECTIVE);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_PROGRESS_HUB, ParagonMoney::_NETWORK_EARN_PROGRESS_HUB);
	 //    NativeHooks::AddHook(NativeHooks::ALL_SCRIPTS, NativeIndex::_NETWORK_EARN_GENERIC, ParagonMoney::_NETWORK_EARN_GENERIC);

		LOG(INFO) << "Paragon native hooks initialized";
	}

	void ParagonNativeHooks::ProgressMpSp(rage::scrNativeCallContext* src)
	{
		src->SetReturnValue<bool>(true);
	}

	void ParagonNativeHooks::UseTransactions(rage::scrNativeCallContext* src)
	{
		src->SetReturnValue<bool>(true);
	}

	void ParagonNativeHooks::StatGetInt(rage::scrNativeCallContext* src) {
		const auto hash = src->GetArg<Hash>(0);
		int* out        = src->GetArg<int*>(1);
		switch (hash) {
		case "MP0_CHAR_IS_NGPC_VERSION"_J:
		case "MP1_CHAR_IS_NGPC_VERSION"_J:
		case "MP1_CHAR_IS_NG_VERSION"_J:
		case "MP0_CHAR_IS_NG_VERSION"_J:
		case "MP0_CHAR_IS_NG_VERSION_SA"_J:
		case "MP1_CHAR_IS_NG_VERSION_SA"_J:
			*out             = 1;
			src->SetReturnValue<INT>(1);
			return;
		default:
			src->SetReturnValue<INT>(STATS::STAT_GET_INT(hash, out, src->GetArg<int>(2)));
		}
	}
}
