//
// Created by troplo on 12/8/25.
//

#ifndef PARAGONMONEY_H
#define PARAGONMONEY_H
#include "core/util/Joaat.hpp"
#include "types/script/scrNativeHandler.hpp"
#include "types/script/types.hpp"

namespace YimMenu
{
	class ParagonMoney {
	enum UpdateType
	{
		INCREMENT,
		DECREMENT,
		SET
	};
	private:
		static bool EarnCash(long long _amount, bool toBank, const joaat_t statId, joaat_t multiplierTunable);
		static bool SpendCash(long long _amount, bool toBank, const joaat_t statId);
		static bool UpdateStat(joaat_t stat, long long amount, UpdateType type);
	public:
		// AUTOGENERATED
	    static void NETWORK_EARN_FROM_PICKUP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_CASHING_OUT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_GANGATTACK_PICKUP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ASSASSINATE_TARGET_KILLED(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_ROB_ARMORED_CARS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_CRATE_DROP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_BETTING(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_JOB(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_JOBX2(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_PREMIUM_JOB(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_BEND_JOB(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_CHALLENGE_WIN(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_BOUNTY(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_IMPORT_EXPORT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_HOLDUPS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_PROPERTY(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_AI_TARGET_KILL(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_NOT_BADSPORT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_VEHICLE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_PERSONAL_VEHICLE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_DAILY_OBJECTIVES(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_AMBIENT_JOB(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_JOB_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_CRIMINAL_MASTERMIND(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_HEIST_AWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FIRST_TIME_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GOON(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_BOSS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AGENCY(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_WAREHOUSE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_CONTRABAND(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_DESTROYING_CONTRABAND(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_SMUGGLER_WORK(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_HANGAR_TRADE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_PURCHASE_CLUB_HOUSE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_BUSINESS_PRODUCT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_VEHICLE_EXPORT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_SMUGGLER_AGENCY(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_BOUNTY_HUNTER_REWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_BUSINESS_BATTLE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_CLUB_MANAGEMENT_PARTICIPATION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_FMBB_PHONECALL_MISSION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_BUSINESS_HUB_SELL(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_FMBB_BOSS_WORK(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FMBB_WAGE_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_GOON(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BOSS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_SELL_BUNKER(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_RDR_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_WAGE_PAYMENT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_WAGE_PAYMENT_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_GANGOPS_CANNON(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_GANGOPS_SKIP_MISSION(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CASINO_HEIST_SKIP_MISSION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_SELL_BASE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_TARGET_REFUND(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GANGOPS_WAGES(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GANGOPS_WAGES_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_DAR_CHALLENGE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_DOOMSDAY_FINALE_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GANGOPS_AWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GANGOPS_ELITE(rage::scrNativeCallContext* src);
	    static void NETWORK_SERVICE_EARN_GANGOPS_RIVAL_DELIVERY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_GANGOPS_START_STRAND(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_GANGOPS_TRIP_SKIP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GANGOPS_PREP_PARTICIPATION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GANGOPS_SETUP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_GANGOPS_FINALE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_GANGOPS_REPAIR_COST(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_NIGHTCLUB(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_NIGHTCLUB_DANCING(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_BB_EVENT_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_HACKER_TRUCK(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_NIGHTCLUB_AND_WAREHOUSE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_NIGHTCLUB_AND_WAREHOUSE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_NIGHTCLUB_BAR_DRINK(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BOUNTY_HUNTER_MISSION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ARENA_SKILL_LEVEL_PROGRESSION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ARENA_CAREER_PROGRESSION(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_MAKE_IT_RAIN(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BUY_ARENA(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_UPGRADE_ARENA(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_ARENA_SPECTATOR_BOX(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_SPIN_THE_WHEEL_PAYMENT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_SPIN_THE_WHEEL_CASH(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_ARENA_PREMIUM(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ARENA_WAR(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ARENA_WAR_ASSASSINATE_TARGET(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ARENA_WAR_EVENT_CARGO(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_RC_TIME_TRIAL(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_DAILY_OBJECTIVE_EVENT(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CASINO_MEMBERSHIP(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BUY_CASINO(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_UPGRADE_CASINO(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CASINO_GENERIC(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_TIME_TRIAL_WIN(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_COLLECTABLES_ACTION_FIGURES(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_COLLECTABLE_COMPLETED_COLLECTION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_SELL_PRIZE_VEHICLE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_MISSION_REWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_STORY_MISSION_REWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_MISSION_PARTICIPATION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_AWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BUY_ARCADE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_UPGRADE_ARCADE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CASINO_HEIST(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_ARCADE_MGMT(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_PLAY_ARCADE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_ARCADE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_HEIST(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_UPGRADE_ARCADE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ARCADE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_COLLECTABLES(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CHALLENGE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CASINO_HEIST_AWARDS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_COLLECTABLE_ITEM(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_COLLECTABLE_COMPLETED_COLLECTION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_YATCH_MISSION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_DISPATCH_CALL(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BEACH_PARTY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_SUBMARINE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CASINO_CLUB(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BUY_SUB(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_UPGRADE_SUB(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_ISLAND_HEIST(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_ISLAND_HEIST(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_BEACH_PARTY_LOST_FOUND(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FROM_ISLAND_HEIST_DJ_MISSION(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CAR_CLUB_MEMBERSHIP(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CAR_CLUB_BAR(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_AUTOSHOP_MODIFY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_CAR_CLUB_TAKEOVER(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BUY_AUTOSHOP(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_UPGRADE_AUTOSHOP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AUTOSHOP_BUSINESS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AUTOSHOP_INCOME(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_CARCLUB_MEMBERSHIP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_DAILY_VEHICLE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_DAILY_VEHICLE_BONUS(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_TUNER_AWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_TUNER_ROBBERY(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_UPGRADE_AUTOSHOP(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_INTERACTION_MENU_ABILITY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BUY_AGENCY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_UPGRADE_AGENCY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_AGENCY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_HIDDEN(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_SOURCE_BIKE(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_COMP_SUV(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_SUV_FST_TRVL(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_SUPPLY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BIKE_SHOP(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_VEHICLE_REQUESTED(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_GUNRUNNING(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AGENCY_SAFE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AWARD_CONTRACT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AGENCY_CONTRACT(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AWARD_PHONE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AGENCY_PHONE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AWARD_FIXER_MISSION(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FIXER_PREP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FIXER_FINALE(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FIXER_AGENCY_SHORT_TRIP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_AWARD_SHORT_TRIP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_FIXER_RIVAL_DELIVERY(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_UPGRADE_AGENCY(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_APARTMENT_UTILITIES(rage::scrNativeCallContext* src);
	    static void NETWORK_SPEND_BUSINESS_PROPERTY_FEES(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_SIGHTSEEING_REWARD(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_BIKER_SHOP(rage::scrNativeCallContext* src);
	    static void NETWORK_EARN_BIKER(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_BUY_MFGARAGE(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_UPGRADE_MFGARAGE(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_BUY_SUPPLIES(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_BUY_ACID_LAB(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_UPGRADE_ACID_LAB_EQUIPMENT(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_UPGRADE_ACID_LAB_ARMOR(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_UPGRADE_ACID_LAB_SCOOP(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_UPGRADE_ACID_LAB_MINES(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_RENAME_ACID_LAB(rage::scrNativeCallContext* src);
	    static void _NETWORK_SPEND_RENAME_ACID_PRODUCT(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_AWARD_JUGGALO_MISSION(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_AWARD_ACID_LAB(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_AWARD_DAILY_STASH(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_AWARD_DEAD_DROP(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_AWARD_RANDOM_EVENT(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_AWARD_TAXI(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_STREET_DEALER(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_SELL_ACID(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_SETUP_PARTICIPATION_ACID_LAB(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_SOURCE_PARTICIPATION_ACID_LAB(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_SELL_PARTICIPATION_ACID_LAB(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_JUGGALO_STORY_MISSION(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_JUGGALO_STORY_MISSION_PARTICIPATION(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_FOOLIGAN_JOB(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_FOOLIGAN_JOB_PARTICIPATION(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_TAXI_JOB(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_DAILY_STASH_HOUSE_COMPLETED(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_DAILY_STASH_HOUSE_PARTICIPATION(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_AVENGER(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_SMUGGLER_OPS(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_BONUS_OBJECTIVE(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_PROGRESS_HUB(rage::scrNativeCallContext* src);
	    static void _NETWORK_EARN_GENERIC(rage::scrNativeCallContext* src);
	};
}



#endif //PARAGONMONEY_H
