//
// Created by troplo on 12/8/25.
//

#include "ParagonMoney.h"

#include "game/frontend/submenus/Recovery/StatEditor.hpp"
#include "game/gta/Natives.hpp"
#include "game/pointers/Pointers.hpp"
#include "types/stats/CStatsMgr.hpp"

namespace YimMenu
{
	int ParagonMoney::GetCurrentSlot()
	{
		auto statValue = Pointers.StatsMgr->GetStat("MPPLY_LAST_MP_CHAR"_J);
		return statValue->GetInt();
	}

	bool ParagonMoney::UpdateStat(joaat_t stat, long long amount, UpdateType type)
	{
		// HARD LIMIT
		if (amount > 100000000)
		{
			LOG(FATAL) << "Money earn is over hard limit, value: " << amount;
			return false;
		}

		#if ENABLE_PARAGON_DEBUGGING
		LOG(INFO) << stat << " " << amount << " " << type;
		#endif

		auto statValue = Pointers.StatsMgr->GetStat(stat);
		#if ENABLE_PARAGON_DEBUGGING
		auto oldValue = statValue->GetInt64();
		#endif
		auto newValue = statValue->GetInt64();

		switch (type)
		{
		case INCREMENT:
			newValue += amount;
			break;
		case DECREMENT:
			newValue -= amount;
			break;
		case SET:
			newValue -= amount;
			break;
		}

		if (newValue < 0)
		{
			LOG(FATAL) << "Money earn will result in negative value, amount: " << amount << " statValue: " << newValue;
			return false;
		}

		statValue->SetInt64(newValue);
		#if ENABLE_PARAGON_DEBUGGING
		auto updatedValue = Pointers.StatsMgr->GetStat(stat);
		LOG(VERBOSE) << "Old value: " << oldValue << " New value: " << newValue << " Updated value: " << updatedValue->GetInt64();
		#endif

		return true;
	}

	bool ParagonMoney::EarnCash(long long _amount, bool toBank, joaat_t statId, joaat_t multiplierTunable)
	{
		LOG(VERBOSE) << "EARN CASH";
		LOG(VERBOSE) << "AMOUNT" << _amount;
		auto amount = _amount;

		if (amount > 0)
		{
			if (!UpdateStat("MPPLY_TOTAL_EVC"_J, amount, INCREMENT))
			{
				return false;
			};
		}
		//
		// if (statId)
		// {
		//
		// 	int slot = MISC::GET_CHOSEN_MP_CHARACTER_SLOT();
		// 	Joaat(slot == 0 ? "MP0_" : "MP1_" + statId);
		// 	if (!UpdateStat(statId, amount, INCREMENT))
		// 	{
		// 		return false;
		// 	}
		// }

		if (toBank)
		{
			if (!UpdateStat("BANK_BALANCE"_J, amount, INCREMENT))
			{
				return false;
			}
		}
		else
		{
			// wallet
			int slot = GetCurrentSlot();
			joaat_t hash = 0;
			if (slot == 0)
			{
				hash = "MP0_WALLET_BALANCE"_J;
			}
			else if (slot == 1)
			{
				hash = "MP1_WALLET_BALANCE"_J;
			}
			else
			{
				LOG(FATAL) << "Invalid slot for transaction: " << slot;
			}

			if (hash)
			{
				if (!UpdateStat(hash, amount, INCREMENT))
				{
					return false;
				}
			}
		}

		return true;
	}

	bool ParagonMoney::SpendCash(long long amount, bool toBank, const joaat_t statId)
	{
		if (amount > 0)
		{
			if (!UpdateStat("MPPLY_TOTAL_EVC"_J, amount, DECREMENT))
			{
				return false;
			};
		}

		if (statId)
		{
			if (!UpdateStat(statId, amount, DECREMENT))
			{
				return false;
			}
		}

		if (toBank)
		{
			if (!UpdateStat("BANK_BALANCE"_J, amount, DECREMENT))
			{
				return false;
			}
		}
		else
		{
			// wallet
			int slot = MISC::GET_CHOSEN_MP_CHARACTER_SLOT();
			joaat_t hash = 0;
			if (slot == 0)
			{
				hash = "MP0_WALLET_BALANCE"_J;
			}
			else if (slot == 1)
			{
				hash = "MP1_WALLET_BALANCE"_J;
			}
			else
			{
				LOG(FATAL) << "Invalid slot for transaction: " << slot;
			}

			if (hash)
			{
				if (!UpdateStat(hash, amount, DECREMENT))
				{
					return false;
				}
			}
		}

		return true;
	}


	// AUTOGENERATED

void ParagonMoney::NETWORK_EARN_FROM_PICKUP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_CASHING_OUT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_GANGATTACK_PICKUP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_ASSASSINATE_TARGET_KILLED(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_ROB_ARMORED_CARS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_CRATE_DROP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_BETTING(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_JOB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    // EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
	MONEY::NETWORK_EARN_FROM_JOB(src->GetArg<int>(0), src->GetArg<const char*>(1));
}

void ParagonMoney::NETWORK_EARN_FROM_JOBX2(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_PREMIUM_JOB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_BEND_JOB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_CHALLENGE_WIN(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_BOUNTY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_IMPORT_EXPORT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_HOLDUPS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_PROPERTY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_AI_TARGET_KILL(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_NOT_BADSPORT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_VEHICLE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_PERSONAL_VEHICLE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_DAILY_OBJECTIVES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_AMBIENT_JOB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_JOB_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_CRIMINAL_MASTERMIND(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_HEIST_AWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FIRST_TIME_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_GOON(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_BOSS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AGENCY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_WAREHOUSE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_CONTRABAND(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_DESTROYING_CONTRABAND(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_SMUGGLER_WORK(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_HANGAR_TRADE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_PURCHASE_CLUB_HOUSE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_BUSINESS_PRODUCT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_VEHICLE_EXPORT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_SMUGGLER_AGENCY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_BOUNTY_HUNTER_REWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_BUSINESS_BATTLE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_CLUB_MANAGEMENT_PARTICIPATION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_FMBB_PHONECALL_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_BUSINESS_HUB_SELL(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_FMBB_BOSS_WORK(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FMBB_WAGE_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_GOON(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(2);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BOSS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_SELL_BUNKER(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_RDR_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_WAGE_PAYMENT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_WAGE_PAYMENT_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_GANGOPS_CANNON(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_GANGOPS_SKIP_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_CASINO_HEIST_SKIP_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_SELL_BASE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_TARGET_REFUND(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_GANGOPS_WAGES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_GANGOPS_WAGES_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_DAR_CHALLENGE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_DOOMSDAY_FINALE_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_GANGOPS_AWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_GANGOPS_ELITE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SERVICE_EARN_GANGOPS_RIVAL_DELIVERY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto earnedMoney = src->GetArg<int>(0);
    EarnCash(earnedMoney, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_GANGOPS_START_STRAND(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(1);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_GANGOPS_TRIP_SKIP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_GANGOPS_PREP_PARTICIPATION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_GANGOPS_SETUP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_GANGOPS_FINALE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_GANGOPS_REPAIR_COST(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_NIGHTCLUB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_NIGHTCLUB_DANCING(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_BB_EVENT_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_HACKER_TRUCK(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(1);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_NIGHTCLUB_AND_WAREHOUSE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_NIGHTCLUB_AND_WAREHOUSE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_NIGHTCLUB_BAR_DRINK(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BOUNTY_HUNTER_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_ARENA_SKILL_LEVEL_PROGRESSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_ARENA_CAREER_PROGRESSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_MAKE_IT_RAIN(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BUY_ARENA(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_UPGRADE_ARENA(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_ARENA_SPECTATOR_BOX(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_SPIN_THE_WHEEL_PAYMENT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_SPIN_THE_WHEEL_CASH(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_ARENA_PREMIUM(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_ARENA_WAR(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_ARENA_WAR_ASSASSINATE_TARGET(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_ARENA_WAR_EVENT_CARGO(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_RC_TIME_TRIAL(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_DAILY_OBJECTIVE_EVENT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_CASINO_MEMBERSHIP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BUY_CASINO(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_UPGRADE_CASINO(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_CASINO_GENERIC(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_TIME_TRIAL_WIN(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_COLLECTABLES_ACTION_FIGURES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_COLLECTABLE_COMPLETED_COLLECTION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_SELL_PRIZE_VEHICLE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_MISSION_REWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_STORY_MISSION_REWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_MISSION_PARTICIPATION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_AWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_BUY_ARCADE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_UPGRADE_ARCADE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_CASINO_HEIST(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_ARCADE_MGMT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_PLAY_ARCADE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_ARCADE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_HEIST(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_UPGRADE_ARCADE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_ARCADE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_COLLECTABLES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CHALLENGE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CASINO_HEIST_AWARDS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_COLLECTABLE_ITEM(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_COLLECTABLE_COMPLETED_COLLECTION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_YATCH_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_DISPATCH_CALL(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_BEACH_PARTY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_SUBMARINE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_CASINO_CLUB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount1 = src->GetArg<int>(0);
    SpendCash(amount1, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BUY_SUB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_UPGRADE_SUB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_ISLAND_HEIST(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_ISLAND_HEIST(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount1 = src->GetArg<int>(0);
    EarnCash(amount1, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_BEACH_PARTY_LOST_FOUND(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FROM_ISLAND_HEIST_DJ_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_CAR_CLUB_MEMBERSHIP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount1 = src->GetArg<int>(0);
    SpendCash(amount1, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_CAR_CLUB_BAR(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_AUTOSHOP_MODIFY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_CAR_CLUB_TAKEOVER(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BUY_AUTOSHOP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_UPGRADE_AUTOSHOP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_AUTOSHOP_BUSINESS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AUTOSHOP_INCOME(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_CARCLUB_MEMBERSHIP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_DAILY_VEHICLE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_DAILY_VEHICLE_BONUS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_TUNER_AWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_TUNER_ROBBERY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_UPGRADE_AUTOSHOP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_INTERACTION_MENU_ABILITY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BUY_AGENCY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_UPGRADE_AGENCY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_AGENCY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_HIDDEN(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_SOURCE_BIKE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_COMP_SUV(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_SUV_FST_TRVL(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_SUPPLY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BIKE_SHOP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_VEHICLE_REQUESTED(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_GUNRUNNING(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_AGENCY_SAFE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AWARD_CONTRACT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AGENCY_CONTRACT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AWARD_PHONE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AGENCY_PHONE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AWARD_FIXER_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FIXER_PREP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FIXER_FINALE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FIXER_AGENCY_SHORT_TRIP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_AWARD_SHORT_TRIP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_FIXER_RIVAL_DELIVERY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_UPGRADE_AGENCY(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_SPEND_APARTMENT_UTILITIES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    SpendCash(amount, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_SPEND_BUSINESS_PROPERTY_FEES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::NETWORK_EARN_SIGHTSEEING_REWARD(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_BIKER_SHOP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::NETWORK_EARN_BIKER(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_SPEND_BUY_MFGARAGE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_UPGRADE_MFGARAGE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_BUY_SUPPLIES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_BUY_ACID_LAB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_EQUIPMENT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_ARMOR(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_SCOOP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_UPGRADE_ACID_LAB_MINES(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_RENAME_ACID_LAB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_SPEND_RENAME_ACID_PRODUCT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    SpendCash(p0, false, "MONEY_SPEND_JOBS"_J);
}

void ParagonMoney::_NETWORK_EARN_AWARD_JUGGALO_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_AWARD_ACID_LAB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_AWARD_DAILY_STASH(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_AWARD_DEAD_DROP(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_AWARD_RANDOM_EVENT(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_AWARD_TAXI(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_STREET_DEALER(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_SELL_ACID(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_SETUP_PARTICIPATION_ACID_LAB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_SOURCE_PARTICIPATION_ACID_LAB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_SELL_PARTICIPATION_ACID_LAB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_JUGGALO_STORY_MISSION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_JUGGALO_STORY_MISSION_PARTICIPATION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_FOOLIGAN_JOB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_FOOLIGAN_JOB_PARTICIPATION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_TAXI_JOB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_DAILY_STASH_HOUSE_COMPLETED(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_DAILY_STASH_HOUSE_PARTICIPATION(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_AVENGER(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_SMUGGLER_OPS(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_BONUS_OBJECTIVE(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_PROGRESS_HUB(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto p0 = src->GetArg<int>(0);
    EarnCash(p0, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

void ParagonMoney::_NETWORK_EARN_GENERIC(rage::scrNativeCallContext* src)
{
    LOG(INFO) << __FUNCTION__;
    const auto amount = src->GetArg<int>(0);
    EarnCash(amount, false, "MONEY_EARN_JOBS"_J, "TROPLOROS_MONEY_MULTIPLIER_JOB_HARD_LIMIT"_J);
}

}